# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # General code quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
      - id: check-toml
      - id: check-xml
      - id: detect-private-key
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Security - Secret Detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock.json|yarn.lock|bun.lockb

  # Security - Gitleaks
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks

  # JavaScript/TypeScript specific
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.56.0
          - eslint-config-prettier@9.1.0
          - eslint-plugin-security@2.1.0
          - '@typescript-eslint/parser@6.19.0'
          - '@typescript-eslint/eslint-plugin@6.19.0'

  # Prettier formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [css, javascript, jsx, ts, tsx, markdown, yaml, json]
        exclude: package-lock.json|yarn.lock|bun.lockb

  # Security - Safety check for Python dependencies (if any)
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check
        files: requirements.*\.txt$

  # Security - Bandit for Python code (if any)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ['-ll', '-i']
        files: \.py$

  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: ['--fix']

  # Security - npm audit
  - repo: local
    hooks:
      - id: npm-audit
        name: npm audit
        entry: bash -c 'npm audit --production --audit-level=moderate || true'
        language: system
        pass_filenames: false
        files: package\.json$

  # Security - Check for vulnerable dependencies
  - repo: local
    hooks:
      - id: check-vulnerabilities
        name: Check for vulnerabilities
        entry: bash -c 'npx audit-ci --moderate || true'
        language: system
        pass_filenames: false
        files: package\.json$

  # TypeScript type checking
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript type check
        entry: bash -c 'npm run type-check || true'
        language: system
        pass_filenames: false
        types: [typescript]

  # Prevent committing sensitive files
  - repo: local
    hooks:
      - id: forbid-sensitive-files
        name: Forbid committing sensitive files
        entry: bash -c '! git diff --cached --name-only | grep -E "(\.env$|\.env\.local$|\.env\.production$|\.pem$|\.key$|\.cert$|\.crt$)"'
        language: system
        pass_filenames: false

# Configuration
default_language_version:
  python: python3.11
  node: 20.11.0

fail_fast: false
exclude: |
  (?x)^(
    node_modules/|
    dist/|
    build/|
    \.next/|
    coverage/|
    \.git/|
    \.vscode/|
    \.idea/|
    package-lock\.json|
    yarn\.lock|
    bun\.lockb|
    \.min\.js$|
    \.min\.css$
  )
