name: Sarif JSON Report Generator
description: Reads a Sarif JSON file and generates a static HTML file as a report.
inputs:
  in:
    description: Name of the Sarif JSON file to look for.
    required: false
    default: scan.sarif.json
  out:
    description: Name of the generated HTML file for the report.
    required: false
    default: report.html
runs:
  using: composite
  steps:
    - name: Install bash and dependencies
      shell: sh
      run: |
        apk add --no-cache bash curl unzip libstdc++ libgcc

    - name: Install Bun
      shell: bash
      run: |
        # Try official installer first, fallback to manual
        if curl -fsSL https://bun.sh/install | bash; then
          echo "Bun installed via official installer"
        else
          echo "Official installer failed, installing manually"
          mkdir -p "$HOME/.bun/bin"
          curl -fsSL "https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip" -o /tmp/bun.zip
          unzip -q /tmp/bun.zip -d /tmp/
          mv /tmp/bun-linux-x64/bun "$HOME/.bun/bin/bun"
          chmod +x "$HOME/.bun/bin/bun"
          rm -rf /tmp/bun.zip /tmp/bun-linux-x64
        fi
        echo "$HOME/.bun/bin" >> $GITHUB_PATH

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ICF-Next-Government/icf-sarif-viewer
        path: .sarif-viewer
        ref: main

    - name: Install dependencies
      shell: bash
      run: cd .sarif-viewer && bun i

    - name: FILES
      shell: bash
      run: ls -la

    # - uses: oven-sh/setup-bun@v2
    #
    # - name: Install Bun
    #   run: curl -fsSL https://bun.sh/install | bash
    #   shell: sh
    #
    # - name: Add Bun to PATH
    #   run: echo "$HOME/.bun/bin" >> $GITHUB_PATH
    #   shell: sh
    #
    # - name: Verify Bun installation
    #   run: bun --version
    #   shell: sh
    #
    # - name: Checkout code
    #   uses: actions/checkout@v4
    #   with:
    #     repository: ICF-Next-Government/icf-sarif-viewer
    #     path: .sarif-viewer
    #     ref: main
    #
    # - name: Generate Sarif Report
    #   run: bun src/cli/generate-html-report.ts --input ${{ inputs.in }} --output ${{ inputs.out }}
    #   shell: sh
    #   working-directory: .sarif-viewer
