name: Sarif JSON Report Generator
description: Reads a Sarif JSON file and generates a static HTML file as a report.
inputs:
  in:
    description: Name of the Sarif JSON file to look for.
    required: false
    default: scan.sarif.json
  out:
    description: Name of the generated HTML file for the report.
    required: false
    default: report.html
runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ICF-Next-Government/icf-sarif-viewer
        path: .sarif-viewer
        ref: main
    - name: Generate Sarif Report
      run: bun src/cli/generate-html-report.ts --input ${{ inputs.in }} --output ${{ inputs.out }}
      shell: sh
      working-directory: .sarif-viewer
