name: Sarif JSON Report Generator
description: Reads a Sarif JSON file and generates a static HTML file as a report.
inputs:
  in:
    description: Name of the Sarif JSON file to look for.
    required: false
    default: scan.sarif.json
  out:
    description: Name of the generated HTML file for the report.
    required: false
    default: report.html
runs:
  using: composite
  steps:
    - name: Install dependencies and Bun
      shell: sh
      run: |
        # Try different package managers and download tools
        if command -v apk >/dev/null 2>&1; then
          apk add --no-cache curl unzip || apk add --no-cache wget unzip
        elif command -v apt-get >/dev/null 2>&1; then
          apt-get update && apt-get install -y curl unzip
        elif command -v yum >/dev/null 2>&1; then
          yum install -y curl unzip
        fi

        # Try curl first, then wget
        if command -v curl >/dev/null 2>&1; then
          curl -fsSL https://bun.sh/install | sh
        elif command -v wget >/dev/null 2>&1; then
          wget -qO- https://bun.sh/install | sh
        else
          echo "Neither curl nor wget available"
          exit 1
        fi
        echo "$HOME/.bun/bin" >> $GITHUB_PATH

    - name: Verify Bun installation
      run: $HOME/.bun/bin/bun --version
      shell: sh

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ICF-Next-Government/icf-sarif-viewer
        path: .sarif-viewer
        ref: main

    - name: Generate Sarif Report
      run: $HOME/.bun/bin/bun src/cli/generate-html-report.ts --input ${{ inputs.in }} --output ${{ inputs.out }}
      shell: sh
      working-directory: .sarif-viewer

    # - uses: oven-sh/setup-bun@v2
    #
    # - name: Install Bun
    #   run: curl -fsSL https://bun.sh/install | bash
    #   shell: sh
    #
    # - name: Add Bun to PATH
    #   run: echo "$HOME/.bun/bin" >> $GITHUB_PATH
    #   shell: sh
    #
    # - name: Verify Bun installation
    #   run: bun --version
    #   shell: sh
    #
    # - name: Checkout code
    #   uses: actions/checkout@v4
    #   with:
    #     repository: ICF-Next-Government/icf-sarif-viewer
    #     path: .sarif-viewer
    #     ref: main
    #
    # - name: Generate Sarif Report
    #   run: bun src/cli/generate-html-report.ts --input ${{ inputs.in }} --output ${{ inputs.out }}
    #   shell: sh
    #   working-directory: .sarif-viewer
