name: Sarif JSON Report Generator
description: Reads a Sarif JSON file and generates a static HTML file as a report.
inputs:
  in:
    description: Name of the Sarif JSON file to look for.
    required: false
    default: scan.sarif.json
  out:
    description: Name of the generated HTML file for the report.
    required: false
    default: report.html
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: .sarif-viewer
        repository: ICF-Next-Government/icf-sarif-viewer
        ref: main

    - name: LIST THINGS
      shell: sh
      run: |
        echo "PWD"
        ls -la

        echo "\nBACK ONE"
        ls -la ..

    # - name: Generate Sarif Report
    #   run: bun src/cli/generate-html-report.ts --input ../${{ inputs.in }} --output ../${{ inputs.out }}
    #   shell: bash
